### ISSUE TITLE
the bot close the game

### ISSUE THREAD

**Issue by Sacher13** [Clintoxen/PUBG-Afk-FarmBot#2]
hi bro, when i push start in the bot, close the game, i choose the resolution 1080 and play pug in max window

**Comment by Clintoxen** [comment]
You are using the gui bot? 

You need to run it in borderless window mode and not fullscreen. Also the bot will autoclose any copies of the game that is already open

**Comment by Karriff** [comment]
https://www.virustotal.com/#/file/591fbb6ae3c405a376783bb8d1c673beb9b5c3fd638a7aa89a6cdaf617deea6c/detection

**Comment by Sacher13** [comment]
yes i run it in borderless window, and now the bot dont do nothing, he dont click in the play section, i try whit all the resolutions

**Comment by Clintoxen** [comment]
Are you using reshade?

**Comment by Clintoxen** [comment]
try the new release it should fix it https://github.com/Clintoxen/PUBG-Afk-FarmBot/releases/tag/1.05

**Comment by Traaka** [comment]
I have the exact same problem I run the bot I have a 1920x1080. I'm not using reshade. I even tried to reset NVIDIA control panel to its normal default, still not working. I press "Start" pubg just turns off.
I tried all the different screens none worked :(

**Comment by Clintoxen** [comment]
@Traaka Have you tried the new bot I linked? Should fix all the issues, I tested it

**Comment by Traaka** [comment]
Yes I tried the version you linked, GUI. Just keeps crashing the game :( Do I need any other programs installed or something?

**Comment by Clintoxen** [comment]
Have you deleted anything in the folder afk bot folder? only reason I can think of it crashing like that is if it is looking for a file and it isnt found. 

The game shouldnt be crashing tho, try restarting your computer, download a new copy and delete the old ones. T

ry running the new copy and let me know if it works. If not ill have to make a debug version of the bot that shows me what errors you are getting.

**Comment by Traaka** [comment]
I restarted pc, got a new install (the one you linked) Keeps crashing the game. It's a fresh install from the one you linked so no I havnt touched any other files then the .EXE

**Comment by Clintoxen** [comment]
alright
try running the debug version and tell me what error it gives you(copy and paste the error into a code tag in a comment) 
https://github.com/Clintoxen/PUBG-Afk-FarmBot/releases/download/1.05/AfkBot.1.05.debug.zip

**Comment by Traaka** [comment]
The CMD (Debug) window crashes with the game and bot at the same time.

**Comment by Clintoxen** [comment]
run this without quotes in a new cmd/powershell window(you can open one in the folder by shift + right click)  and run "PUBG AfkBot 1.05.exe"  

it should show you the error

**Comment by Traaka** [comment]
I opend powershell and and wrote in "PUBG AfkBot 1.05.exe" And got this back.

`PUBG : The term 'PUBG' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ PUBG AfkBot 1.05.exe
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (PUBG:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by Traaka** [comment]
I also realised a while after i run the bot my computer gets super slow and super laggy? hmmm...

**Comment by Clintoxen** [comment]
my bad try to run it with the quotes 

start "PUBG AfkBot 1.05.exe" 

let me know what it says @Traaka try restarting your computer again if its running slow, idk about that unless some process isnt closing properly

**Comment by Clintoxen** [comment]
If it comes down to it you may be better off just using the "old source code" branch and cloning that and running the bot without the gui!

**Comment by Traaka** [comment]
The debug CMD window instantly closes when I run the command in PowerShell hmm?

**Comment by Clintoxen** [comment]
Ok the powershell should tell you what error it received, in all honestly without being able to see the error I cant tell you exactly what is happening. I cant replicate the issue, do you have an discord we can jump in real quick before i go to sleep

**Comment by Clintoxen** [comment]
If you dont mind restarting and trying this version, if this doesnt work then idk man. Just delete the other version and place this in the folder
[PUBG AfkBot 1.00.exe.zip](https://github.com/Clintoxen/PUBG-Afk-FarmBot/files/1443778/PUBG.AfkBot.1.00.exe.zip)

**Comment by Traaka** [comment]
@Clintoxen Nope, it dosn't work. Eh what ever guess i'll just have to get it by playing :/

**Comment by Clintoxen** [comment]
Welp, that was like a complete barebones version of the bot.  only other thing could be that your environmental variables are not set, so it cant load the config. 

can you make sure these are in your enviromental variables? 

![image](https://user-images.githubusercontent.com/20504430/32412098-933f118a-c1c3-11e7-9da2-0fe390ff02e8.png)

https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

**Comment by Clintoxen** [comment]
Also like I said https://github.com/Clintoxen/PUBG-Afk-FarmBot/tree/Old-Code works pretty much the same way without the gui but only for 1080p. If you have python installed then its quick to set up

**Comment by Traaka** [comment]
The enviromental variables are set. I have python 3.6 not sure how to set it up tho

**Comment by Traaka** [comment]
"AfkBot1.py" CMD window also instantly crashes.. :/

**Comment by dustyroo** [comment]
Google search 'how to setup python path in windows (ie 10 or whatever you have )'

**Comment by Traaka** [comment]
@dustyroo I did set it up correctly. CMD window just crashes..

**Comment by dustyroo** [comment]
download the .exe and run it

**Comment by dustyroo** [comment]
if that does not work. go into a random folder and hit Shift+right click then click 'Open PowerShell window here' if you do not have windows 10 do this in cmd. 
type: - you can copy paste like normal if you do this in powershell
pip install pyautogui
pip install psutil
pip install Pillow

if you cant install then you do not have the enviromental variables set

**Comment by dustyroo** [comment]
![cmonbruh-profile_image-84cf1a6644b6e42a-300x300](https://user-images.githubusercontent.com/12129838/32414961-8987290e-c1ee-11e7-97d3-7271d19907db.png)

**Comment by Traaka** [comment]
Whaaaat! That actually works. Starting the BOT before running the game omg.. Thanks man!

**Comment by Traaka** [comment]
Well thats fixed now theres another problem it keeps opening settings after a couple of minutes into the game :/

**Comment by Clintoxen** [comment]
Brooooo are you serious lmao that was the problem??? 😂. I assumed you started the bot while the game was closed, glad it worked. Thanks for the help @dustyroo

**Comment by Clintoxen** [comment]
It should be opening the esc menu and leaving the game, not the settings menu

**Comment by Traaka** [comment]
Hahah yeeh >.< I assumed I had to start it while the game was running, Now it just goes into settings and stays there.
